version: '3.8'

services:
  geography-db:
    image: maxkhal/geography-db:2
    container_name: geography-db
    hostname: geography-db
    ports:
      - '27017:27017'
    env_file: .env.db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - geography-network
  geography-server:
    image: maxkhal/geography-server:2
    hostname: geography-server
    container_name: server
    depends_on:
      geography-db:
        condition: service_healthy
    ports:
      - '4000:4000'
    env_file: .env.srv
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - geography-network
  geography-frontend:
    image: maxkhal/geography-frontend:5
    container_name: frontend
    hostname: geography-frontend
    depends_on:
      geography-server:
        condition: service_healthy
    ports:
      - '3000:3000'
    env_file:
      - .env.ui
    networks:
      - geography-network

networks:
    geography-network:
        driver: bridge
