FROM node:20-alpine
LABEL mantainer="xadmax@gmail.com"

WORKDIR /usr/src/app
ENV MONGODB_URL="mongodb://admin:admin@geography-db:27017/geographydb?authSource=admin"

COPY package.json /usr/src/app
RUN npm install
COPY . .
RUN sed -i 's/\r$//' wait-mongo.sh

EXPOSE 4000
USER node
CMD ["node", "app.js"]
